// Code generated by "stringer -type Code"; DO NOT EDIT.

package er

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UncaughtException-0]
}

const (
	_Code_name_0 = "UncaughtException"
)

var (
	_Code_index_0 = [...]uint16{0}
)

func (i Code) String() string {
	switch {
	case 0 <= i && i <= 17:
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
